package com.srgpanov.simpleweather.other

const val WIDGET_ICONS = "WIDGET_ICONS"
const val WIDGET_LIGHT_THEME = "WIDGET_LIGHT_THEME"
const val WIDGET_SHOW_TIME_UPDATE = "WIDGET_SHOW_TIME_UPDATE"
const val WIDGET_TRANSPARENCY = "WIDGET_TRANSPARENCY"
const val WIDGET_LOCATION_TYPE = "WIDGET_LOCATION_TYPE"
const val WIDGET_LOCATION_NAME = "WIDGET_LOCATION_NAME"

const val WIDGET_LATITUDE = "WIDGET_LATITUDE"
const val WIDGET_LONGITUDE = "WIDGET_LONGITUDE"


const val REFRESH_TIME = 7200000L //2 hour
const val WEATHER_IS_ACTUAL = 43200000L // 12 hours